### ISSUE TITLE
when i call func newTopic,how to set partition number?and how many default partitions

### ISSUE THREAD

**Issue by ayamzh** [php-rdkafka/php-rdkafka#243] opened 2019-07-24 05:50 UTC
$rk = new \RdKafka\Producer();
        $rk->setLogLevel(LOG_DEBUG);
        $rk->addBrokers("127.0.0.1:9092");

        $topic = $rk->newTopic("test");

**Comment by nick-zh** [comment] 2019-07-24 06:26
@ayamzh when you create a topic on the broker, you define how many partitions you want. The default setting on the broker, which is `num.partitions` is set to 1.
With either `produce` and `producev` you can either give a partition you want, or set `RD_KAFKA_PARTITION_UA` (unassigned) which will take the default partitioner. As far as i remember the default is a random partitioner, but you could set others with `RdKafka\TopicConf::setPartitioner`.
I hope this helps :)

**Comment by ayamzh** [comment] 2019-07-24 06:49
can you give me an example  code,hot to use php-rdkafka  set the partition number of the new topic

**Comment by nick-zh** [comment] 2019-07-24 07:02
@ayamzh i am not sure if i understand correct. You cannot create the topic / partition with PHP since the Admin API is not exposed (https://github.com/arnaud-lb/php-rdkafka/issues/215). `newTopic` does not create a new topic, it creates an instance of a topic that you need for the consumer.

**Comment by nick-zh** [comment] 2019-07-24 08:32
@ayamzh let me know if you need further help or if we can resolve this

**Comment by ayamzh** [comment] 2019-07-24 08:35
thanks very much,  i just see #215 , the struct has  "num_partitions" 
/**
 * @name CreateTopics
 * @{
 */

/**
 * @brief NewTopic type, used with CreateTopics.
 */
struct rd_kafka_NewTopic_s {
        /* Required */
        char *topic;            /**< Topic to be created */
        int num_partitions;     /**< Number of partitions to create */
        int replication_factor; /**< Replication factor */

        /* Optional */
        rd_list_t replicas;     /**< Type (rd_list_t (int32_t)):
                                 *   Array of replica lists indexed by
                                 *   partition, size num_partitions. */
        rd_list_t config;       /**< Type (rd_kafka_ConfigEntry_t *):
                                 *   List of configuration entries */
};

**Comment by Steveb-p** [comment] 2019-07-24 08:36
@ayamzh You're referencing librdkafka API that Nick specifically said earlier is not implemented yet in phprdkafka (#215)

**Comment by ayamzh** [comment] 2019-07-24 08:37
the kafka  config/server.properties's num.partitions , is the partitions default value when i use php client to call newTopic,  but

**Comment by ayamzh** [comment] 2019-07-24 08:39
> @ayamzh thanks a lot , if you can help me to reslove it . i need the newTopic function can set the partition num of the topic

**Comment by ayamzh** [comment] 2019-07-24 08:42
> @ayamzh let me know if you need further help or if we can resolve this

thanks a lot , if you can help me to reslove it . i need the newTopic function can set the partition num of the topic

**Comment by nick-zh** [comment] 2019-07-24 08:42
@ayamzh this function is available in https://github.com/edenhill/librdkafka, the php extension (which this project is), does not implement all the functionality that librdkafka offers. #215 is what we need to do to add support for what you are asking. Right now we cannot do this in PHP. Hope this clarification helps :wink: 
**Update:** So i think this can be closed, since it is a duplicate of  #215, but you can subscribe to #215 to track progress if you want.

**Comment by ayamzh** [comment] 2019-07-24 10:48
@nick-zh thanks.i  have subscribed #215 ,i look forward you to reslove it

**Comment by nick-zh** [comment] 2019-07-24 10:53
@ayamzh perfect, this can be closed then

**Closed as completed** 2019-07-26 09:06 UTC
