### ISSUE TITLE
Windows php client？

### ISSUE THREAD

**Issue by qzc77** [php-rdkafka/php-rdkafka#61] opened 2016-06-29 04:07 UTC
Usually developed and debugged in the windows environment? Is there an extension to the Windows version?

**Comment by arnaud-lb** [comment] 2016-06-29 08:44
Hi @qzc77 

The extension may build under windows, however I've never tried. I would gladly accept contributions on this :)

I'm closing this ticket because it's a duplicate of #13, #29.

**Closed as completed by arnaud-lb** 2016-06-29 08:44 UTC
