### ISSUE TITLE
RdKafka\KafkaConsumer::offsetsForTimes is undefined

### ISSUE THREAD

**Issue by bugreporter001** [php-rdkafka/php-rdkafka#190] opened 2018-11-03 07:33 UTC
Fatal error: Uncaught Error: Call to undefined method RdKafka\KafkaConsumer::offsetsForTimes()

**Comment by nick-zh** [comment] 2019-04-23 06:48
this is a duplicate of #130 this method right now is not yet supported

**Closed as completed** 2019-04-23 08:23 UTC
