### ISSUE TITLE
Class 'RdKafka\Producer' not found

### ISSUE THREAD

**Issue by arielconti10** [php-rdkafka/php-rdkafka#165] opened 2018-03-22 20:03 UTC
Class 'RdKafka\Producer' not found

result of php -i 
rdkafka support => enabled
version => 3.0.5
build date => Mar 20 2018 21:22:11
librdkafka version (runtime) => 0.11.4-RC2
librdkafka version (build) => 0.11.0.0

the lib are ok, but not working.

**Comment by scaytrase** [comment] 2018-03-23 13:17
Looks like duplicate of #160

**Closed as completed** 2018-03-26 10:46 UTC
